variable "rg_info" {}
variable "server_info" {}
variable "database_info" {}
variable "vnet_info" {}
variable "subnet_info" {}
variable "nic_info" {}
variable "vm_info" {}
variable "publicip_info" {}
variable "nsg_info" {}
variable "nsg_nic_association" {}